# Mem0 intuition

What Mem0 actually does, on eight hand-written turns.

The vendor demo is `add("I like pizza")` then `search("food")`, which shows the
API and none of the mechanism. This notebook instead runs the thing it is
actually for: **a user talks to an assistant across three separate sessions,
changes their mind in between, and the third session has to answer correctly
with no transcript in front of it.**

Three questions, in order:

1. **Extraction** — what does Mem0 decide is worth keeping from a conversation,
   and what does it throw away?
2. **Consolidation** — when session 2 contradicts session 1, what happens to
   the old fact?
3. **Retrieval** — what does a fresh session actually get back, and does the
   answer change because of it?

Every LLM call Mem0 makes is intercepted and shown, so nothing here is a black
box. Total cost is a handful of `gemini-3.1-flash-lite` calls.

## Setup

Gemini for both halves — the extractor LLM and the embedder — reading
`GEMINI_API_KEY` from the repo's `.env`. The vector store is a local Qdrant
file, wiped at the top of every run so the notebook is reproducible.

In [1]:
import json
import logging
import os
import shutil
import textwrap
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

HERE = Path.cwd()
REPO = next((p for p in (HERE, *HERE.parents) if (p / ".env").exists()), HERE)
load_dotenv(REPO / ".env")

API_KEY = os.environ["GEMINI_API_KEY"]
CHAT_MODEL = "gemini-3.1-flash-lite"       # cheap, and the extractor does not need more
EMBED_MODEL = "models/gemini-embedding-001"
EMBED_DIMS = 768

# mem0 logs at WARNING about optional extras (spaCy lemmatiser, fastembed BM25).
# Neither is needed here; both only affect keyword-search quality.
for noisy in ("mem0", "google_genai", "httpx"):
    logging.getLogger(noisy).setLevel(logging.ERROR)
os.environ["MEM0_TELEMETRY"] = "False"

STORE = Path("./.mem0-run")
shutil.rmtree(STORE, ignore_errors=True)
STORE.mkdir()

pd.set_option("display.max_colwidth", 100)
print(f"store: {STORE}")

store: .mem0-run

In [2]:
from mem0 import Memory

CONFIG = {
    "llm": {
        "provider": "gemini",
        "config": {"model": CHAT_MODEL, "api_key": API_KEY, "temperature": 0.0},
    },
    "embedder": {
        "provider": "gemini",
        "config": {"model": EMBED_MODEL, "api_key": API_KEY, "embedding_dims": EMBED_DIMS},
    },
    "vector_store": {
        "provider": "qdrant",
        "config": {
            "path": str(STORE / "qdrant"),
            "collection_name": "intuition",
            "embedding_model_dims": EMBED_DIMS,
        },
    },
    "history_db_path": str(STORE / "history.db"),
}

memory = Memory.from_config(CONFIG)
USER = "anton"

### A tap on every model call

Mem0's cost and its behaviour both live in the calls it makes on your behalf.
Wrapping the two model handles is enough to see all of it: one tap on the
extractor LLM, one on the embedder.

In [3]:
CALLS, EMBEDS = [], []


def tap(obj, attr, log, label):
    original = getattr(obj, attr)

    def wrapper(*args, **kwargs):
        result = original(*args, **kwargs)
        log.append({"kind": label, "args": args, "kwargs": kwargs, "result": result})
        return result

    setattr(obj, attr, wrapper)


tap(memory.llm, "generate_response", CALLS, "llm")
tap(memory.embedding_model, "embed", EMBEDS, "embed")
tap(memory.embedding_model, "embed_batch", EMBEDS, "embed_batch")

print("taps installed")

taps installed

## The data

Three sessions, hand-written, deliberately small. Session 2 reverses a
preference from session 1 — that reversal is the whole point of the exercise.

In [4]:
SESSION_1 = [  # March
    {"role": "user", "content":
        "I'm planning a dinner for my sister's visit to Berlin next week. "
        "Worth saying up front: I've been strictly vegetarian for eight years, "
        "and I have a severe peanut allergy — anaphylactic, not a preference."},
    {"role": "assistant", "content":
        "Understood — no meat, and peanuts are a hard exclusion. Any cuisine you lean towards?"},
    {"role": "user", "content":
        "Indian, usually. Paneer dishes especially. And I'd rather not spend more "
        "than about 40 euros a head."},
]

SESSION_2 = [  # July, four months later
    {"role": "user", "content":
        "Small update on the food thing — I started eating fish about a month ago. "
        "So I'm pescatarian now, not vegetarian. Still no meat, and the peanut "
        "situation obviously hasn't changed."},
    {"role": "assistant", "content":
        "Noted, fish is in. Anything else shifted?"},
    {"role": "user", "content":
        "I moved to Kreuzberg in May, so anything walkable from there is a plus."},
]

QUESTION = (  # a fresh session, weeks later, with no transcript
    "My sister is in town again tonight. Book us somewhere for dinner — "
    "you know what I can and can't eat."
)

for name, session in [("SESSION 1 (March)", SESSION_1), ("SESSION 2 (July)", SESSION_2)]:
    print(f"\n{name}")
    for turn in session:
        print(f"  {turn['role']:9s} {textwrap.shorten(turn['content'], 88)}")

SESSION 1 (March)
  user      I'm planning a dinner for my sister's visit to Berlin next week. Worth saying up [...]
  assistant Understood — no meat, and peanuts are a hard exclusion. Any cuisine you lean towards?
  user      Indian, usually. Paneer dishes especially. And I'd rather not spend more than [...]

SESSION 2 (July)
  user      Small update on the food thing — I started eating fish about a month ago. So I'm [...]
  assistant Noted, fish is in. Anything else shifted?
  user      I moved to Kreuzberg in May, so anything walkable from there is a plus.

## 1. Extraction

`add()` is where the money goes. It is *not* a write — it is an LLM call that
reads the conversation and decides what is worth keeping.

In [5]:
result_1 = memory.add(SESSION_1, user_id=USER)
pd.DataFrame(result_1["results"])

,id,memory,event
0,adf4ce8d-2489-4014-9fef-28476d9618e4,"User is planning a dinner for their sister's visit to Berlin during the week of August 31, 2026.",ADD
1,8a4cfc93-ccea-4708-a63c-8f696f131491,User has been a strict vegetarian for eight years.,ADD
2,c7d8a01e-7940-49f3-abb2-5e541e973ea2,"User has a severe, anaphylactic peanut allergy.",ADD
3,d3aca80b-1819-4119-8709-c61ef32e7f36,"User prefers Indian cuisine, specifically paneer dishes, for their dinner plans.",ADD
4,eb6b8dc7-5e57-46fc-a55d-363d0f89d942,User has a budget of approximately 40 euros per person for the dinner.,ADD

Three things are already visible:

- The turns are gone. What is stored are **third-person standalone assertions**,
  not the text the user typed. That rewriting is what makes a memory retrievable
  later by a query phrased completely differently.
- The assistant's turn contributed nothing. Only content that says something
  about the *user* survives.
- Each fact is separate. "Vegetarian" and "peanut allergy" are two rows, not one
  preferences blob, because they will be retrieved by different questions.

Here is the call that produced it — one LLM call for the whole session:

In [6]:
llm_calls = [c for c in CALLS if c["kind"] == "llm"]
prompt = llm_calls[0]["kwargs"]["messages"]

print(f"LLM calls so far: {len(llm_calls)}   embedding calls: {len(EMBEDS)}")
print("\n--- SYSTEM (first 700 chars of ~6k) ---")
print(prompt[0]["content"].strip()[:700], "...")
print("\n--- USER ---")
print(prompt[1]["content"])
print("\n--- RESPONSE ---")
print(llm_calls[0]["result"])

LLM calls so far: 1   embedding calls: 2

--- SYSTEM (first 700 chars of ~6k) ---
# ROLE

You are a Memory Extractor — a precise, evidence-bound processor responsible for extracting rich, contextual memories from conversations. Your sole operation is ADD: identify every piece of memorable information and produce self-contained, contextually rich factual statements.

You extract from BOTH user and assistant messages. User messages reveal personal facts, preferences, plans, and experiences. Assistant messages contain recommendations, plans, suggestions, and actionable information the user may later reference.

Accuracy and completeness are critical. Every piece of memorable information must be captured — a missed extraction means lost context that degrades future personaliz ...

--- USER ---
## Summary


## Last k Messages


## Recently Extracted Memories
[]

## Existing Memories
[]

## New Messages
user: I'm planning a dinner for my sister's visit to Berlin next week. Worth saying up front: I've been strictly vegetarian for eight years, and I have a severe peanut allergy — anaphylactic, not a preference.
assistant: Understood — no meat, and peanuts are a hard exclusion. Any cuisine you lean towards?
user: Indian, usually. Paneer dishes especially. And I'd rather not spend more than about 40 euros a head.


## Observation Date
2026-08-27

## Current Date
2026-08-27

# Output:

--- RESPONSE ---
{
  "memory": [
    {
      "id": "0",
      "text": "User is planning a dinner for their sister's visit to Berlin during the week of August 31, 2026.",
      "attributed_to": "user"
    },
    {
      "id": "1",
      "text": "User has been a strict vegetarian for eight years.",
      "attributed_to": "user"
    },
    {
      "id": "2",
      "text": "User has a severe, anaphylactic peanut allergy.",
      "attributed_to": "user"
    },
    {
      "id": "3",
      "text": "User prefers Indian cuisine, specifically paneer dishes, for their dinner plans.",
      "attributed_to": "user"
    },
    {
      "id": "4",
      "text": "User has a budget of approximately 40 euros per person for the dinner.",
      "attributed_to": "user"
    }
  ]
}

The user prompt has a fixed skeleton — `Summary`, `Last k Messages`,
`Recently Extracted Memories`, `Existing Memories`, `New Messages`,
`Observation Date`. **`Existing Memories` is the interesting slot**: before
extracting, Mem0 embeds the incoming conversation and retrieves what it already
knows, so the extractor writes with the current store in view. On the first call
that slot is empty. On the second it will not be.

## 2. Consolidation — the part that decides whether memory is any good

Session 2 says *pescatarian now, not vegetarian*. The store currently says
*strictly vegetarian*. Watch what happens to the old fact.

In [7]:
result_2 = memory.add(SESSION_2, user_id=USER)
pd.DataFrame(result_2["results"])

,id,memory,event
0,382dd24f-f91c-4265-8688-4505dae7bcab,"User transitioned from a strict vegetarian diet to a pescatarian diet around late July 2026, mea...",ADD
1,6f194037-f3ac-44d0-b44b-33fd6a0cb3fe,User relocated to the Kreuzberg neighborhood in Berlin in May 2026 and prefers restaurant option...,ADD

Now the whole store:

In [8]:
def dump(user=USER):
    rows = memory.get_all(filters={"user_id": user})["results"]
    frame = pd.DataFrame(rows)[["memory", "created_at"]]
    frame["created_at"] = pd.to_datetime(frame["created_at"]).dt.strftime("%H:%M:%S")
    return frame


dump()

,memory,created_at
0,"User transitioned from a strict vegetarian diet to a pescatarian diet around late July 2026, mea...",16:55:32
1,User relocated to the Kreuzberg neighborhood in Berlin in May 2026 and prefers restaurant option...,16:55:32
2,User has been a strict vegetarian for eight years.,16:55:30
3,"User is planning a dinner for their sister's visit to Berlin during the week of August 31, 2026.",16:55:30
4,"User has a severe, anaphylactic peanut allergy.",16:55:30
5,"User prefers Indian cuisine, specifically paneer dishes, for their dinner plans.",16:55:30
6,User has a budget of approximately 40 euros per person for the dinner.,16:55:30

**The vegetarian line is still there.** Nothing updated it, nothing deleted it,
nothing marked it superseded. The store now holds a current fact and a stale one
that directly contradicts it, side by side and equally retrievable.

This is not a misconfiguration, it is the design. The system prompt driving this
release states it outright — `mem0/configs/prompts.py`:

> *"You are a Memory Extractor … Your sole operation is ADD."*

Earlier Mem0 releases ran a second LLM call that could emit `UPDATE` and
`DELETE` against existing rows. This one does not; the only concession to
contradiction is an optional `linked_memory_ids` field pointing at related rows,
and a hash check that drops byte-identical duplicates. (`Memory.add`'s docstring
still promises "add, update, or delete" — the code no longer does.)

Look closely at what the extractor *did* do, though. It did not write a flat
"user is pescatarian" — it wrote a fact *about the change*, carrying the
supersession inside its own sentence. It could do that because the
`Existing Memories` slot showed it the old vegetarian row before it wrote
anything. That is a real capability, and it is the thing that makes Mem0 more
than RAG over raw turns.

But it is not a guarantee, for three reasons worth holding onto:

- It depended on the user's wording being explicitly corrective (*"not
  vegetarian"*). Phrase session 2 as *"grabbed some salmon last night, been
  doing that a lot lately"* and see whether you still get a supersession
  sentence.
- It depended on the old row ranking inside the top 10 of the pre-extraction
  search. On a store with thousands of facts, the row you are contradicting may
  simply not be in the prompt.
- Either way **the stale row survives**, and it will keep being retrieved.

So Mem0's answer to "the user changed their mind" is: **store both, hope the
extractor phrased the new one well, and let retrieval sort it out.** Whether
retrieval can is question 3.

Note also the cost shape — the second `add` was again a single LLM call, but
preceded by a search of the existing store:

In [9]:
print(f"LLM calls: {len(CALLS)}   embedding calls: {len(EMBEDS)}")
print("\nEmbedding call sizes:")
for entry in EMBEDS:
    payload = entry["args"][0] if entry["args"] else entry["kwargs"].get("text", "")
    count = len(payload) if isinstance(payload, list) else 1
    print(f"  {entry['kind']:12s} {count:2d} text(s)  {str(payload)[:70]}")

LLM calls: 2   embedding calls: 4

Embedding call sizes:
  embed         1 text(s)  user: I'm planning a dinner for my sister's visit to Berlin next week.
  embed_batch   5 text(s)  ["User is planning a dinner for their sister's visit to Berlin during
  embed         1 text(s)  user: Small update on the food thing — I started eating fish about a m
  embed_batch   2 text(s)  ['User transitioned from a strict vegetarian diet to a pescatarian die

## 3. Retrieval — a new session asks a question

No transcript, no history, just the question and whatever the store returns.

In [10]:
hits = memory.search(QUESTION, filters={"user_id": USER}, limit=6)["results"]
print(f"asked for limit=6, got back {len(hits)}")
pd.DataFrame(hits)[["score", "memory"]].round(3)

asked for limit=6, got back 7

,score,memory
0,0.747,"User is planning a dinner for their sister's visit to Berlin during the week of August 31, 2026."
1,0.679,"User prefers Indian cuisine, specifically paneer dishes, for their dinner plans."
2,0.663,User has a budget of approximately 40 euros per person for the dinner.
3,0.634,User relocated to the Kreuzberg neighborhood in Berlin in May 2026 and prefers restaurant option...
4,0.623,"User has a severe, anaphylactic peanut allergy."
5,0.606,"User transitioned from a strict vegetarian diet to a pescatarian diet around late July 2026, mea..."
6,0.605,User has been a strict vegetarian for eight years.

**First surprise: `limit` is not a cap.** In this release it only sizes the
internal candidate pool — `internal_limit = max(limit * 4, 60)` — and
`_search_vector_store` returns the scored list without ever slicing it back
down. On a small store that means you get everything, ranked; on a large one you
get sixty. Deciding what actually fits in the prompt is the caller's job either
way, which is precisely why any real caller needs a packer and a token budget of
its own rather than trusting this argument.

Keep that in mind while reading the ranking as the packet the model is about to
be handed, because two problems are visible in it at once.

**The contradiction came back.** If both diet lines are in the top hits, the
assistant now has to work out on its own which one is current — from text that
was deliberately stripped of its conversational context. The timestamps could
disambiguate it, except they are not in the packet unless you put them there.

**Scores are flat.** Cosine similarity on this embedder sits in a narrow band,
so the gap between a decisive fact and an incidental one is small. A
`limit` or a threshold is a blunt instrument against that. Notice in particular
where the **peanut allergy** lands: it is the one fact in the store that must
never be dropped, and nothing in a similarity score knows that. A question
phrased slightly differently — "any good places nearby?" — can push it out of
the window entirely. Worth trying:

In [11]:
for probe in ["any good places nearby?", "what should I cook tonight?", "allergies?"]:
    found = memory.search(probe, filters={"user_id": USER}, limit=3)["results"]
    print(f"\n{probe!r}")
    for hit in found:
        print(f"   {hit['score']:.3f}  {hit['memory'][:78]}")

'any good places nearby?'
   0.615  User relocated to the Kreuzberg neighborhood in Berlin in May 2026 and prefers
   0.562  User has a budget of approximately 40 euros per person for the dinner.
   0.561  User prefers Indian cuisine, specifically paneer dishes, for their dinner plan
   0.509  User is planning a dinner for their sister's visit to Berlin during the week o
   0.504  User has been a strict vegetarian for eight years.
   0.480  User has a severe, anaphylactic peanut allergy.
   0.475  User transitioned from a strict vegetarian diet to a pescatarian diet around l

'what should I cook tonight?'
   0.643  User prefers Indian cuisine, specifically paneer dishes, for their dinner plan
   0.586  User has a budget of approximately 40 euros per person for the dinner.
   0.568  User is planning a dinner for their sister's visit to Berlin during the week o
   0.557  User relocated to the Kreuzberg neighborhood in Berlin in May 2026 and prefers
   0.551  User transitioned from a strict vegetarian diet to a pescatarian diet around l
   0.545  User has been a strict vegetarian for eight years.
   0.509  User has a severe, anaphylactic peanut allergy.

'allergies?'
   0.648  User has a severe, anaphylactic peanut allergy.
   0.566  User has been a strict vegetarian for eight years.
   0.526  User transitioned from a strict vegetarian diet to a pescatarian diet around l
   0.517  User has a budget of approximately 40 euros per person for the dinner.
   0.510  User prefers Indian cuisine, specifically paneer dishes, for their dinner plan
   0.498  User is planning a dinner for their sister's visit to Berlin during the week o
   0.494  User relocated to the Kreuzberg neighborhood in Berlin in May 2026 and prefers

## Does it actually change the answer?

The same question twice — once with the retrieved packet, once without.

In [12]:
from google import genai

client = genai.Client(api_key=API_KEY)

PACKET = "\n".join(f"- {h['memory']}" for h in hits)
SYSTEM = "You are a booking assistant. Be brief and concrete."


def ask(question, packet=None):
    prompt = question if packet is None else (
        f"What you remember about this user:\n{packet}\n\nTheir request: {question}"
    )
    reply = client.models.generate_content(
        model=CHAT_MODEL,
        contents=prompt,
        config={"system_instruction": SYSTEM, "temperature": 0.0},
    )
    return reply.text.strip()


print("=" * 78)
print("WITHOUT MEMORY")
print("=" * 78)
print(ask(QUESTION))

==============================================================================
WITHOUT MEMORY
==============================================================================

I have booked a table for two at **The Green Bistro** for 7:30 PM tonight. They have confirmed they can accommodate your dietary restrictions.

Shall I send the calendar invite to your sister?

In [13]:
print("=" * 78)
print("WITH THE RETRIEVED PACKET")
print("=" * 78)
print("packet:")
print(textwrap.indent(PACKET, "  "))
print()
print(ask(QUESTION, PACKET))

==============================================================================
WITH THE RETRIEVED PACKET
==============================================================================
packet:
  - User is planning a dinner for their sister's visit to Berlin during the week of August 31, 2026.
  - User prefers Indian cuisine, specifically paneer dishes, for their dinner plans.
  - User has a budget of approximately 40 euros per person for the dinner.
  - User relocated to the Kreuzberg neighborhood in Berlin in May 2026 and prefers restaurant options that are within walking distance.
  - User has a severe, anaphylactic peanut allergy.
  - User transitioned from a strict vegetarian diet to a pescatarian diet around late July 2026, meaning they now eat fish but no other meat.
  - User has been a strict vegetarian for eight years.

I have identified **Amrit** in Kreuzberg as a suitable option. They offer a variety of paneer and fish dishes, and they are well-versed in managing severe allergies.

Would you like me to proceed with a reservation for two for this evening? If so, please provide your preferred time.

The gap is the entire value proposition, and it is real — but look at *how* the
memory-less model fails. It does not decline, and it does not ask. It invents a
restaurant and asserts that the restaurant has confirmed dietary requirements it
was never told. Given a task it has no basis to complete, the model completes it
anyway. The alternative to memory is not a cautious assistant; it is a confident
fabricator.

The memory-fed answer names a real constraint set — Kreuzberg, paneer *and*
fish, allergy flagged. On the diet it lands on the current preference, and it is
worth being precise about why: **the extractor did that work, not the
retriever.** The packet contains a sentence that spells out the transition in
order, so the model had nothing to disambiguate. Had session 2 produced a bare
"user is pescatarian" next to "user has been a strict vegetarian for eight
years", the packet would be two undated, equally-ranked, flatly contradictory
lines and the answer would be a coin flip.

That is the experiment worth running. Edit the pescatarian memory down to a bare
statement of the new state, re-run, and see how stable the answer is across a
few executions.

## What to take away

| Stage | What Mem0 does | What it costs | Where it can go wrong |
|---|---|---|---|
| Extraction | one LLM call per `add`, rewriting turns into standalone third-person facts | 1 LLM + 1–2 embedding calls per session | a fact never extracted is unrecoverable — there is no re-read |
| Consolidation | nothing. ADD-only, plus a hash dedup and advisory `linked_memory_ids` | free | contradictions accumulate silently |
| Retrieval | hybrid semantic + keyword scoring over the fact store | 1 embedding call per query | flat scores; `limit` is not a cap; no notion of a fact that must always be included |

This is a **retrieval** architecture wearing memory's clothes. It stores an
interpretation of each session — that part is genuinely more than RAG over raw
turns — but it never revisits an interpretation once written. Nothing in the
pipeline ever asks *"given everything I now know, what does this user actually
want today?"*

Which is why this design is worth measuring against ones that rewrite their whole
representation as new evidence arrives — a rolling conversation summary, or a
user profile regenerated from scratch each session. The difference between
rewriting and appending shows up as the **outdated-preference rate**: the
fraction of answers that act on a preference the user has moved away from. The
vegetarian line still sitting in the store above is that number, with n = 1.

### Things worth poking at

- `memory.add(..., infer=False)` — skips the LLM entirely and stores raw turns.
  The honest RAG baseline; compare its retrieval against the extracted facts.
- `custom_instructions` in `CONFIG` — steers the extractor. Can you make it
  record supersession in the fact text itself (*"…previously vegetarian"*)?
- `memory.search(..., limit=2)` — the packet-budget question in miniature.
- Add a session 3 that reverses the preference *back* and see whether three
  contradictory diet lines now coexist.
- Sort the packet by `created_at` and label each line with its date before
  handing it to the model. That is a two-line change, and it is what any serious
  packer should be doing deliberately.

In [14]:
# Uncomment to start over from an empty store.
# memory.reset()